version: '3.7'

services:
  solr8n1:
    image: solr:8.5
    container_name: solr8n1
    command: bin/solr -f -h solr8n1
    ports:
     - "8991:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr8n2:
    image: solr:8.5
    container_name: solr8n2
    command: bin/solr -f -h solr8n2
    ports:
     - "8992:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr8n3:
    image: solr:8.5
    container_name: solr8n3
    command: bin/solr -f -h solr8n3
    ports:
     - "8993:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr6n1:
    image: solr:6.6
    container_name: solr6n1
    ports:
        - "8971:8983"
    environment:
        - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
        - solr
    depends_on:
        - zoo1
        - zoo2
        - zoo3

  solr6n2:
    image: solr:6.6
    container_name: solr6n2
    ports:
        - "8972:8983"
    environment:
        - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
        - solr
    depends_on:
        - zoo1
        - zoo2
        - zoo3

  solr6n3:
    image: solr:6.6
    container_name: solr6n3
    ports:
        - "8973:8983"
    environment:
        - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
        - solr
    depends_on:
        - zoo1
        - zoo2
        - zoo3
    
  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr

  zoo2:
    image: zookeeper:3.5
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr

  zoo3:
    image: zookeeper:3.5
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr

networks:
  solr: