version: "3.5"

services:

  db:
    image: postgres:alpine
    volumes:
      - /mnt/nfs/data/collab/postgres:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    ports:
      - 1080:80
    volumes:
      - /mnt/nfs/data/collab/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
    env_file:
      - db.env
    depends_on:
      - db


